// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/api.dart';
import 'api/types.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiApiInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => -1694464673;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_open_tv',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiApiAddLastWatched({required PlatformInt64 id});

  Future<ChannelHttpHeaders> crateApiTypesChannelHttpHeadersDefault();

  Future<void> crateApiApiClearHistory();

  Future<void> crateApiApiCreateOrInitializeDb();

  Future<void> crateApiApiDropDb();

  Future<void> crateApiApiGetEpisodes({required Channel channel});

  Future<void> crateApiApiGetM3U8({required Source source});

  Future<void> crateApiApiGetM3U8FromLink({required Source source});

  Future<Settings> crateApiApiGetSettings();

  Future<String> crateApiApiGetUserAgentFromSource({required Source source});

  Future<void> crateApiApiGetXtream({required Source source});

  Future<bool> crateApiApiHasSources();

  Future<void> crateApiApiInitApp();

  Future<void> crateApiApiRefreshAll();

  Future<void> crateApiApiRefreshSource({required Source source});

  Future<List<Channel>> crateApiApiSearch({required Filters filters});

  Future<Season> crateApiTypesSeasonDefault();

  Future<void> crateApiApiUpdateSettings({required Settings settings});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiApiAddLastWatched({required PlatformInt64 id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiApiAddLastWatchedConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiAddLastWatchedConstMeta =>
      const TaskConstMeta(debugName: "add_last_watched", argNames: ["id"]);

  @override
  Future<ChannelHttpHeaders> crateApiTypesChannelHttpHeadersDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_channel_http_headers,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTypesChannelHttpHeadersDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTypesChannelHttpHeadersDefaultConstMeta =>
      const TaskConstMeta(
        debugName: "channel_http_headers_default",
        argNames: [],
      );

  @override
  Future<void> crateApiApiClearHistory() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiApiClearHistoryConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiClearHistoryConstMeta =>
      const TaskConstMeta(debugName: "clear_history", argNames: []);

  @override
  Future<void> crateApiApiCreateOrInitializeDb() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiApiCreateOrInitializeDbConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiCreateOrInitializeDbConstMeta =>
      const TaskConstMeta(debugName: "create_or_initialize_db", argNames: []);

  @override
  Future<void> crateApiApiDropDb() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiApiDropDbConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiDropDbConstMeta =>
      const TaskConstMeta(debugName: "drop_db", argNames: []);

  @override
  Future<void> crateApiApiGetEpisodes({required Channel channel}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_channel(channel, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiApiGetEpisodesConstMeta,
        argValues: [channel],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiGetEpisodesConstMeta =>
      const TaskConstMeta(debugName: "get_episodes", argNames: ["channel"]);

  @override
  Future<void> crateApiApiGetM3U8({required Source source}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_source(source, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiApiGetM3U8ConstMeta,
        argValues: [source],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiGetM3U8ConstMeta =>
      const TaskConstMeta(debugName: "get_m3u8", argNames: ["source"]);

  @override
  Future<void> crateApiApiGetM3U8FromLink({required Source source}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_source(source, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiApiGetM3U8FromLinkConstMeta,
        argValues: [source],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiGetM3U8FromLinkConstMeta => const TaskConstMeta(
    debugName: "get_m3u8_from_link",
    argNames: ["source"],
  );

  @override
  Future<Settings> crateApiApiGetSettings() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_settings,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiApiGetSettingsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiGetSettingsConstMeta =>
      const TaskConstMeta(debugName: "get_settings", argNames: []);

  @override
  Future<String> crateApiApiGetUserAgentFromSource({required Source source}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_source(source, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiApiGetUserAgentFromSourceConstMeta,
        argValues: [source],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiGetUserAgentFromSourceConstMeta =>
      const TaskConstMeta(
        debugName: "get_user_agent_from_source",
        argNames: ["source"],
      );

  @override
  Future<void> crateApiApiGetXtream({required Source source}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_source(source, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiApiGetXtreamConstMeta,
        argValues: [source],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiGetXtreamConstMeta =>
      const TaskConstMeta(debugName: "get_xtream", argNames: ["source"]);

  @override
  Future<bool> crateApiApiHasSources() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiApiHasSourcesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiHasSourcesConstMeta =>
      const TaskConstMeta(debugName: "has_sources", argNames: []);

  @override
  Future<void> crateApiApiInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiApiInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<void> crateApiApiRefreshAll() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiApiRefreshAllConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiRefreshAllConstMeta =>
      const TaskConstMeta(debugName: "refresh_all", argNames: []);

  @override
  Future<void> crateApiApiRefreshSource({required Source source}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_source(source, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiApiRefreshSourceConstMeta,
        argValues: [source],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiRefreshSourceConstMeta =>
      const TaskConstMeta(debugName: "refresh_source", argNames: ["source"]);

  @override
  Future<List<Channel>> crateApiApiSearch({required Filters filters}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_filters(filters, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_channel,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiApiSearchConstMeta,
        argValues: [filters],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiSearchConstMeta =>
      const TaskConstMeta(debugName: "search", argNames: ["filters"]);

  @override
  Future<Season> crateApiTypesSeasonDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_season,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTypesSeasonDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTypesSeasonDefaultConstMeta =>
      const TaskConstMeta(debugName: "season_default", argNames: []);

  @override
  Future<void> crateApiApiUpdateSettings({required Settings settings}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_settings(settings, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiApiUpdateSettingsConstMeta,
        argValues: [settings],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiUpdateSettingsConstMeta =>
      const TaskConstMeta(debugName: "update_settings", argNames: ["settings"]);

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  Channel dco_decode_box_autoadd_channel(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_channel(raw);
  }

  @protected
  Filters dco_decode_box_autoadd_filters(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_filters(raw);
  }

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_i_64(raw);
  }

  @protected
  Settings dco_decode_box_autoadd_settings(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_settings(raw);
  }

  @protected
  SortType dco_decode_box_autoadd_sort_type(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_sort_type(raw);
  }

  @protected
  Source dco_decode_box_autoadd_source(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_source(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_u_64(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  ViewType dco_decode_box_autoadd_view_type(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_view_type(raw);
  }

  @protected
  Channel dco_decode_channel(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 15)
      throw Exception('unexpected arr length: expect 15 but see ${arr.length}');
    return Channel(
      id: dco_decode_opt_box_autoadd_i_64(arr[0]),
      name: dco_decode_String(arr[1]),
      url: dco_decode_opt_String(arr[2]),
      group: dco_decode_opt_String(arr[3]),
      image: dco_decode_opt_String(arr[4]),
      mediaType: dco_decode_media_type(arr[5]),
      sourceId: dco_decode_opt_box_autoadd_i_64(arr[6]),
      seriesId: dco_decode_opt_box_autoadd_u_64(arr[7]),
      groupId: dco_decode_opt_box_autoadd_i_64(arr[8]),
      favorite: dco_decode_bool(arr[9]),
      streamId: dco_decode_opt_box_autoadd_u_64(arr[10]),
      tvArchive: dco_decode_opt_box_autoadd_bool(arr[11]),
      seasonId: dco_decode_opt_box_autoadd_i_64(arr[12]),
      episodeNum: dco_decode_opt_box_autoadd_i_64(arr[13]),
      hidden: dco_decode_opt_box_autoadd_bool(arr[14]),
    );
  }

  @protected
  ChannelHttpHeaders dco_decode_channel_http_headers(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return ChannelHttpHeaders(
      id: dco_decode_opt_box_autoadd_i_64(arr[0]),
      channelId: dco_decode_opt_box_autoadd_i_64(arr[1]),
      referrer: dco_decode_opt_String(arr[2]),
      userAgent: dco_decode_opt_String(arr[3]),
      httpOrigin: dco_decode_opt_String(arr[4]),
      ignoreSsl: dco_decode_opt_box_autoadd_bool(arr[5]),
    );
  }

  @protected
  Filters dco_decode_filters(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return Filters(
      query: dco_decode_opt_String(arr[0]),
      sourceIds: dco_decode_list_prim_i_64_strict(arr[1]),
      mediaTypes: dco_decode_opt_list_media_type(arr[2]),
      viewType: dco_decode_view_type(arr[3]),
      page: dco_decode_u_8(arr[4]),
      seriesId: dco_decode_opt_box_autoadd_i_64(arr[5]),
      groupId: dco_decode_opt_box_autoadd_i_64(arr[6]),
      useKeywords: dco_decode_bool(arr[7]),
      sort: dco_decode_sort_type(arr[8]),
      season: dco_decode_opt_box_autoadd_i_64(arr[9]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<Channel> dco_decode_list_channel(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_channel).toList();
  }

  @protected
  List<MediaType> dco_decode_list_media_type(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_media_type).toList();
  }

  @protected
  Int64List dco_decode_list_prim_i_64_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeInt64List(raw);
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  MediaType dco_decode_media_type(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MediaType.values[raw as int];
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_bool(raw);
  }

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_64(raw);
  }

  @protected
  SortType? dco_decode_opt_box_autoadd_sort_type(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_sort_type(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_16(raw);
  }

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_64(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_8(raw);
  }

  @protected
  ViewType? dco_decode_opt_box_autoadd_view_type(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_view_type(raw);
  }

  @protected
  List<MediaType>? dco_decode_opt_list_media_type(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_media_type(raw);
  }

  @protected
  Season dco_decode_season(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return Season(
      id: dco_decode_opt_box_autoadd_i_64(arr[0]),
      name: dco_decode_String(arr[1]),
      seasonNumber: dco_decode_i_64(arr[2]),
      image: dco_decode_opt_String(arr[3]),
      seriesId: dco_decode_u_64(arr[4]),
      sourceId: dco_decode_i_64(arr[5]),
    );
  }

  @protected
  Settings dco_decode_settings(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 14)
      throw Exception('unexpected arr length: expect 14 but see ${arr.length}');
    return Settings(
      recordingPath: dco_decode_opt_String(arr[0]),
      mpvParams: dco_decode_opt_String(arr[1]),
      useStreamCaching: dco_decode_opt_box_autoadd_bool(arr[2]),
      defaultView: dco_decode_opt_box_autoadd_view_type(arr[3]),
      volume: dco_decode_opt_box_autoadd_u_8(arr[4]),
      refreshOnStart: dco_decode_opt_box_autoadd_bool(arr[5]),
      restreamPort: dco_decode_opt_box_autoadd_u_16(arr[6]),
      enableTrayIcon: dco_decode_opt_box_autoadd_bool(arr[7]),
      zoom: dco_decode_opt_box_autoadd_u_16(arr[8]),
      defaultSort: dco_decode_opt_box_autoadd_sort_type(arr[9]),
      enableHwdec: dco_decode_opt_box_autoadd_bool(arr[10]),
      alwaysAskSave: dco_decode_opt_box_autoadd_bool(arr[11]),
      enableGpu: dco_decode_opt_box_autoadd_bool(arr[12]),
      forceTvMode: dco_decode_opt_box_autoadd_bool(arr[13]),
    );
  }

  @protected
  SortType dco_decode_sort_type(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SortType.values[raw as int];
  }

  @protected
  Source dco_decode_source(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 13)
      throw Exception('unexpected arr length: expect 13 but see ${arr.length}');
    return Source(
      id: dco_decode_opt_box_autoadd_i_64(arr[0]),
      name: dco_decode_String(arr[1]),
      url: dco_decode_opt_String(arr[2]),
      urlOrigin: dco_decode_opt_String(arr[3]),
      username: dco_decode_opt_String(arr[4]),
      password: dco_decode_opt_String(arr[5]),
      sourceType: dco_decode_source_type(arr[6]),
      useTvgId: dco_decode_opt_box_autoadd_bool(arr[7]),
      enabled: dco_decode_bool(arr[8]),
      userAgent: dco_decode_opt_String(arr[9]),
      maxStreams: dco_decode_opt_box_autoadd_u_8(arr[10]),
      streamUserAgent: dco_decode_opt_String(arr[11]),
      lastUpdated: dco_decode_opt_box_autoadd_i_64(arr[12]),
    );
  }

  @protected
  SourceType dco_decode_source_type(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SourceType.values[raw as int];
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  ViewType dco_decode_view_type(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ViewType.values[raw as int];
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_bool(deserializer));
  }

  @protected
  Channel sse_decode_box_autoadd_channel(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_channel(deserializer));
  }

  @protected
  Filters sse_decode_box_autoadd_filters(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_filters(deserializer));
  }

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_64(deserializer));
  }

  @protected
  Settings sse_decode_box_autoadd_settings(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_settings(deserializer));
  }

  @protected
  SortType sse_decode_box_autoadd_sort_type(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_sort_type(deserializer));
  }

  @protected
  Source sse_decode_box_autoadd_source(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_source(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_16(deserializer));
  }

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_64(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_8(deserializer));
  }

  @protected
  ViewType sse_decode_box_autoadd_view_type(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_view_type(deserializer));
  }

  @protected
  Channel sse_decode_channel(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_url = sse_decode_opt_String(deserializer);
    var var_group = sse_decode_opt_String(deserializer);
    var var_image = sse_decode_opt_String(deserializer);
    var var_mediaType = sse_decode_media_type(deserializer);
    var var_sourceId = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_seriesId = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_groupId = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_favorite = sse_decode_bool(deserializer);
    var var_streamId = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_tvArchive = sse_decode_opt_box_autoadd_bool(deserializer);
    var var_seasonId = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_episodeNum = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_hidden = sse_decode_opt_box_autoadd_bool(deserializer);
    return Channel(
      id: var_id,
      name: var_name,
      url: var_url,
      group: var_group,
      image: var_image,
      mediaType: var_mediaType,
      sourceId: var_sourceId,
      seriesId: var_seriesId,
      groupId: var_groupId,
      favorite: var_favorite,
      streamId: var_streamId,
      tvArchive: var_tvArchive,
      seasonId: var_seasonId,
      episodeNum: var_episodeNum,
      hidden: var_hidden,
    );
  }

  @protected
  ChannelHttpHeaders sse_decode_channel_http_headers(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_channelId = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_referrer = sse_decode_opt_String(deserializer);
    var var_userAgent = sse_decode_opt_String(deserializer);
    var var_httpOrigin = sse_decode_opt_String(deserializer);
    var var_ignoreSsl = sse_decode_opt_box_autoadd_bool(deserializer);
    return ChannelHttpHeaders(
      id: var_id,
      channelId: var_channelId,
      referrer: var_referrer,
      userAgent: var_userAgent,
      httpOrigin: var_httpOrigin,
      ignoreSsl: var_ignoreSsl,
    );
  }

  @protected
  Filters sse_decode_filters(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_query = sse_decode_opt_String(deserializer);
    var var_sourceIds = sse_decode_list_prim_i_64_strict(deserializer);
    var var_mediaTypes = sse_decode_opt_list_media_type(deserializer);
    var var_viewType = sse_decode_view_type(deserializer);
    var var_page = sse_decode_u_8(deserializer);
    var var_seriesId = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_groupId = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_useKeywords = sse_decode_bool(deserializer);
    var var_sort = sse_decode_sort_type(deserializer);
    var var_season = sse_decode_opt_box_autoadd_i_64(deserializer);
    return Filters(
      query: var_query,
      sourceIds: var_sourceIds,
      mediaTypes: var_mediaTypes,
      viewType: var_viewType,
      page: var_page,
      seriesId: var_seriesId,
      groupId: var_groupId,
      useKeywords: var_useKeywords,
      sort: var_sort,
      season: var_season,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<Channel> sse_decode_list_channel(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Channel>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_channel(deserializer));
    }
    return ans_;
  }

  @protected
  List<MediaType> sse_decode_list_media_type(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <MediaType>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_media_type(deserializer));
    }
    return ans_;
  }

  @protected
  Int64List sse_decode_list_prim_i_64_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getInt64List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  MediaType sse_decode_media_type(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return MediaType.values[inner];
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_bool(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  SortType? sse_decode_opt_box_autoadd_sort_type(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_sort_type(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_16(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_8(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ViewType? sse_decode_opt_box_autoadd_view_type(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_view_type(deserializer));
    } else {
      return null;
    }
  }

  @protected
  List<MediaType>? sse_decode_opt_list_media_type(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_media_type(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Season sse_decode_season(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_seasonNumber = sse_decode_i_64(deserializer);
    var var_image = sse_decode_opt_String(deserializer);
    var var_seriesId = sse_decode_u_64(deserializer);
    var var_sourceId = sse_decode_i_64(deserializer);
    return Season(
      id: var_id,
      name: var_name,
      seasonNumber: var_seasonNumber,
      image: var_image,
      seriesId: var_seriesId,
      sourceId: var_sourceId,
    );
  }

  @protected
  Settings sse_decode_settings(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_recordingPath = sse_decode_opt_String(deserializer);
    var var_mpvParams = sse_decode_opt_String(deserializer);
    var var_useStreamCaching = sse_decode_opt_box_autoadd_bool(deserializer);
    var var_defaultView = sse_decode_opt_box_autoadd_view_type(deserializer);
    var var_volume = sse_decode_opt_box_autoadd_u_8(deserializer);
    var var_refreshOnStart = sse_decode_opt_box_autoadd_bool(deserializer);
    var var_restreamPort = sse_decode_opt_box_autoadd_u_16(deserializer);
    var var_enableTrayIcon = sse_decode_opt_box_autoadd_bool(deserializer);
    var var_zoom = sse_decode_opt_box_autoadd_u_16(deserializer);
    var var_defaultSort = sse_decode_opt_box_autoadd_sort_type(deserializer);
    var var_enableHwdec = sse_decode_opt_box_autoadd_bool(deserializer);
    var var_alwaysAskSave = sse_decode_opt_box_autoadd_bool(deserializer);
    var var_enableGpu = sse_decode_opt_box_autoadd_bool(deserializer);
    var var_forceTvMode = sse_decode_opt_box_autoadd_bool(deserializer);
    return Settings(
      recordingPath: var_recordingPath,
      mpvParams: var_mpvParams,
      useStreamCaching: var_useStreamCaching,
      defaultView: var_defaultView,
      volume: var_volume,
      refreshOnStart: var_refreshOnStart,
      restreamPort: var_restreamPort,
      enableTrayIcon: var_enableTrayIcon,
      zoom: var_zoom,
      defaultSort: var_defaultSort,
      enableHwdec: var_enableHwdec,
      alwaysAskSave: var_alwaysAskSave,
      enableGpu: var_enableGpu,
      forceTvMode: var_forceTvMode,
    );
  }

  @protected
  SortType sse_decode_sort_type(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return SortType.values[inner];
  }

  @protected
  Source sse_decode_source(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_url = sse_decode_opt_String(deserializer);
    var var_urlOrigin = sse_decode_opt_String(deserializer);
    var var_username = sse_decode_opt_String(deserializer);
    var var_password = sse_decode_opt_String(deserializer);
    var var_sourceType = sse_decode_source_type(deserializer);
    var var_useTvgId = sse_decode_opt_box_autoadd_bool(deserializer);
    var var_enabled = sse_decode_bool(deserializer);
    var var_userAgent = sse_decode_opt_String(deserializer);
    var var_maxStreams = sse_decode_opt_box_autoadd_u_8(deserializer);
    var var_streamUserAgent = sse_decode_opt_String(deserializer);
    var var_lastUpdated = sse_decode_opt_box_autoadd_i_64(deserializer);
    return Source(
      id: var_id,
      name: var_name,
      url: var_url,
      urlOrigin: var_urlOrigin,
      username: var_username,
      password: var_password,
      sourceType: var_sourceType,
      useTvgId: var_useTvgId,
      enabled: var_enabled,
      userAgent: var_userAgent,
      maxStreams: var_maxStreams,
      streamUserAgent: var_streamUserAgent,
      lastUpdated: var_lastUpdated,
    );
  }

  @protected
  SourceType sse_decode_source_type(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return SourceType.values[inner];
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  ViewType sse_decode_view_type(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ViewType.values[inner];
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_channel(Channel self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_channel(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_filters(Filters self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_filters(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_settings(
    Settings self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_settings(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_sort_type(
    SortType self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_sort_type(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_source(Source self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_source(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_16(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_8(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_view_type(
    ViewType self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_view_type(self, serializer);
  }

  @protected
  void sse_encode_channel(Channel self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_box_autoadd_i_64(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_opt_String(self.url, serializer);
    sse_encode_opt_String(self.group, serializer);
    sse_encode_opt_String(self.image, serializer);
    sse_encode_media_type(self.mediaType, serializer);
    sse_encode_opt_box_autoadd_i_64(self.sourceId, serializer);
    sse_encode_opt_box_autoadd_u_64(self.seriesId, serializer);
    sse_encode_opt_box_autoadd_i_64(self.groupId, serializer);
    sse_encode_bool(self.favorite, serializer);
    sse_encode_opt_box_autoadd_u_64(self.streamId, serializer);
    sse_encode_opt_box_autoadd_bool(self.tvArchive, serializer);
    sse_encode_opt_box_autoadd_i_64(self.seasonId, serializer);
    sse_encode_opt_box_autoadd_i_64(self.episodeNum, serializer);
    sse_encode_opt_box_autoadd_bool(self.hidden, serializer);
  }

  @protected
  void sse_encode_channel_http_headers(
    ChannelHttpHeaders self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_box_autoadd_i_64(self.id, serializer);
    sse_encode_opt_box_autoadd_i_64(self.channelId, serializer);
    sse_encode_opt_String(self.referrer, serializer);
    sse_encode_opt_String(self.userAgent, serializer);
    sse_encode_opt_String(self.httpOrigin, serializer);
    sse_encode_opt_box_autoadd_bool(self.ignoreSsl, serializer);
  }

  @protected
  void sse_encode_filters(Filters self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_String(self.query, serializer);
    sse_encode_list_prim_i_64_strict(self.sourceIds, serializer);
    sse_encode_opt_list_media_type(self.mediaTypes, serializer);
    sse_encode_view_type(self.viewType, serializer);
    sse_encode_u_8(self.page, serializer);
    sse_encode_opt_box_autoadd_i_64(self.seriesId, serializer);
    sse_encode_opt_box_autoadd_i_64(self.groupId, serializer);
    sse_encode_bool(self.useKeywords, serializer);
    sse_encode_sort_type(self.sort, serializer);
    sse_encode_opt_box_autoadd_i_64(self.season, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_channel(List<Channel> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_channel(item, serializer);
    }
  }

  @protected
  void sse_encode_list_media_type(
    List<MediaType> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_media_type(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_i_64_strict(
    Int64List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putInt64List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_media_type(MediaType self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_bool(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_sort_type(
    SortType? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_sort_type(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_16(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_16(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_8(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_8(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_view_type(
    ViewType? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_view_type(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_list_media_type(
    List<MediaType>? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_media_type(self, serializer);
    }
  }

  @protected
  void sse_encode_season(Season self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_box_autoadd_i_64(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_i_64(self.seasonNumber, serializer);
    sse_encode_opt_String(self.image, serializer);
    sse_encode_u_64(self.seriesId, serializer);
    sse_encode_i_64(self.sourceId, serializer);
  }

  @protected
  void sse_encode_settings(Settings self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_String(self.recordingPath, serializer);
    sse_encode_opt_String(self.mpvParams, serializer);
    sse_encode_opt_box_autoadd_bool(self.useStreamCaching, serializer);
    sse_encode_opt_box_autoadd_view_type(self.defaultView, serializer);
    sse_encode_opt_box_autoadd_u_8(self.volume, serializer);
    sse_encode_opt_box_autoadd_bool(self.refreshOnStart, serializer);
    sse_encode_opt_box_autoadd_u_16(self.restreamPort, serializer);
    sse_encode_opt_box_autoadd_bool(self.enableTrayIcon, serializer);
    sse_encode_opt_box_autoadd_u_16(self.zoom, serializer);
    sse_encode_opt_box_autoadd_sort_type(self.defaultSort, serializer);
    sse_encode_opt_box_autoadd_bool(self.enableHwdec, serializer);
    sse_encode_opt_box_autoadd_bool(self.alwaysAskSave, serializer);
    sse_encode_opt_box_autoadd_bool(self.enableGpu, serializer);
    sse_encode_opt_box_autoadd_bool(self.forceTvMode, serializer);
  }

  @protected
  void sse_encode_sort_type(SortType self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_source(Source self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_box_autoadd_i_64(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_opt_String(self.url, serializer);
    sse_encode_opt_String(self.urlOrigin, serializer);
    sse_encode_opt_String(self.username, serializer);
    sse_encode_opt_String(self.password, serializer);
    sse_encode_source_type(self.sourceType, serializer);
    sse_encode_opt_box_autoadd_bool(self.useTvgId, serializer);
    sse_encode_bool(self.enabled, serializer);
    sse_encode_opt_String(self.userAgent, serializer);
    sse_encode_opt_box_autoadd_u_8(self.maxStreams, serializer);
    sse_encode_opt_String(self.streamUserAgent, serializer);
    sse_encode_opt_box_autoadd_i_64(self.lastUpdated, serializer);
  }

  @protected
  void sse_encode_source_type(SourceType self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_view_type(ViewType self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }
}
