// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

Future<void> getM3U8({required Source source}) =>
    RustLib.instance.api.crateApiApiGetM3U8(source: source);

Future<void> getM3U8FromLink({required Source source}) =>
    RustLib.instance.api.crateApiApiGetM3U8FromLink(source: source);

Future<Settings> getSettings() => RustLib.instance.api.crateApiApiGetSettings();

Future<void> updateSettings({required Settings settings}) =>
    RustLib.instance.api.crateApiApiUpdateSettings(settings: settings);

Future<List<Channel>> search({required Filters filters}) =>
    RustLib.instance.api.crateApiApiSearch(filters: filters);

Future<void> getXtream({required Source source}) =>
    RustLib.instance.api.crateApiApiGetXtream(source: source);

Future<void> getEpisodes({required Channel channel}) =>
    RustLib.instance.api.crateApiApiGetEpisodes(channel: channel);

Future<void> createOrInitializeDb() =>
    RustLib.instance.api.crateApiApiCreateOrInitializeDb();

Future<void> dropDb() => RustLib.instance.api.crateApiApiDropDb();

Future<void> refreshSource({required Source source}) =>
    RustLib.instance.api.crateApiApiRefreshSource(source: source);

Future<void> addSource({required Source source}) =>
    RustLib.instance.api.crateApiApiAddSource(source: source);

Future<void> refreshAll() => RustLib.instance.api.crateApiApiRefreshAll();

Future<String> getUserAgentFromSource({required Source source}) =>
    RustLib.instance.api.crateApiApiGetUserAgentFromSource(source: source);

Future<void> addLastWatched({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiApiAddLastWatched(id: id);

Future<void> clearHistory() => RustLib.instance.api.crateApiApiClearHistory();

Future<bool> hasSources() => RustLib.instance.api.crateApiApiHasSources();

Future<List<Source>> getSources() =>
    RustLib.instance.api.crateApiApiGetSources();

Future<bool> sourceNameExists({required String name}) =>
    RustLib.instance.api.crateApiApiSourceNameExists(name: name);

Future<void> updateLastSeenVersion({required String version}) =>
    RustLib.instance.api.crateApiApiUpdateLastSeenVersion(version: version);

Future<void> setSourceEnabled({
  required bool value,
  required PlatformInt64 sourceId,
}) => RustLib.instance.api.crateApiApiSetSourceEnabled(
  value: value,
  sourceId: sourceId,
);

Future<void> deleteSource({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiApiDeleteSource(id: id);
