// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

// These functions are ignored because they are not marked as `pub`: `commit_channel`, `extract_non_empty_capture`, `get_channel_from_lines`, `get_media_type`, `get_tmp_path`, `set_http_headers`, `try_commit_channel`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `M3UProcessing`

Future<void> readM3U8({required Source source, required bool wipe}) =>
    RustLib.instance.api.crateApiM3UReadM3U8(source: source, wipe: wipe);

Future<void> getM3U8FromLink({required Source source, required bool wipe}) =>
    RustLib.instance.api.crateApiM3UGetM3U8FromLink(source: source, wipe: wipe);
