// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'media_type.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'sort_type.dart';
import 'source_type.dart';
import 'view_type.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ChannelPreserve`, `CustomChannelExtraData`, `CustomChannel`, `ExportedGroup`, `ExportedSource`, `Group`, `IdName`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

class Channel {
  final PlatformInt64? id;
  final String name;
  final String? url;
  final String? group;
  final String? image;
  final MediaType mediaType;
  final PlatformInt64? sourceId;
  final BigInt? seriesId;
  final PlatformInt64? groupId;
  final bool favorite;
  final BigInt? streamId;
  final bool? tvArchive;
  final PlatformInt64? seasonId;
  final PlatformInt64? episodeNum;
  final bool? hidden;

  const Channel({
    this.id,
    required this.name,
    this.url,
    this.group,
    this.image,
    required this.mediaType,
    this.sourceId,
    this.seriesId,
    this.groupId,
    required this.favorite,
    this.streamId,
    this.tvArchive,
    this.seasonId,
    this.episodeNum,
    this.hidden,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      url.hashCode ^
      group.hashCode ^
      image.hashCode ^
      mediaType.hashCode ^
      sourceId.hashCode ^
      seriesId.hashCode ^
      groupId.hashCode ^
      favorite.hashCode ^
      streamId.hashCode ^
      tvArchive.hashCode ^
      seasonId.hashCode ^
      episodeNum.hashCode ^
      hidden.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Channel &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          url == other.url &&
          group == other.group &&
          image == other.image &&
          mediaType == other.mediaType &&
          sourceId == other.sourceId &&
          seriesId == other.seriesId &&
          groupId == other.groupId &&
          favorite == other.favorite &&
          streamId == other.streamId &&
          tvArchive == other.tvArchive &&
          seasonId == other.seasonId &&
          episodeNum == other.episodeNum &&
          hidden == other.hidden;
}

class ChannelHttpHeaders {
  final PlatformInt64? id;
  final PlatformInt64? channelId;
  final String? referrer;
  final String? userAgent;
  final String? httpOrigin;
  final bool? ignoreSsl;

  const ChannelHttpHeaders({
    this.id,
    this.channelId,
    this.referrer,
    this.userAgent,
    this.httpOrigin,
    this.ignoreSsl,
  });

  static Future<ChannelHttpHeaders> default_() =>
      RustLib.instance.api.crateApiTypesChannelHttpHeadersDefault();

  @override
  int get hashCode =>
      id.hashCode ^
      channelId.hashCode ^
      referrer.hashCode ^
      userAgent.hashCode ^
      httpOrigin.hashCode ^
      ignoreSsl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChannelHttpHeaders &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          channelId == other.channelId &&
          referrer == other.referrer &&
          userAgent == other.userAgent &&
          httpOrigin == other.httpOrigin &&
          ignoreSsl == other.ignoreSsl;
}

class Filters {
  final String? query;
  final Int64List sourceIds;
  final List<MediaType>? mediaTypes;
  final ViewType viewType;
  final int page;
  final PlatformInt64? seriesId;
  final PlatformInt64? groupId;
  final bool useKeywords;
  final SortType sort;
  final PlatformInt64? season;

  const Filters({
    this.query,
    required this.sourceIds,
    this.mediaTypes,
    required this.viewType,
    required this.page,
    this.seriesId,
    this.groupId,
    required this.useKeywords,
    required this.sort,
    this.season,
  });

  @override
  int get hashCode =>
      query.hashCode ^
      sourceIds.hashCode ^
      mediaTypes.hashCode ^
      viewType.hashCode ^
      page.hashCode ^
      seriesId.hashCode ^
      groupId.hashCode ^
      useKeywords.hashCode ^
      sort.hashCode ^
      season.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Filters &&
          runtimeType == other.runtimeType &&
          query == other.query &&
          sourceIds == other.sourceIds &&
          mediaTypes == other.mediaTypes &&
          viewType == other.viewType &&
          page == other.page &&
          seriesId == other.seriesId &&
          groupId == other.groupId &&
          useKeywords == other.useKeywords &&
          sort == other.sort &&
          season == other.season;
}

class Season {
  final PlatformInt64? id;
  final String name;
  final PlatformInt64 seasonNumber;
  final String? image;
  final BigInt seriesId;
  final PlatformInt64 sourceId;

  const Season({
    this.id,
    required this.name,
    required this.seasonNumber,
    this.image,
    required this.seriesId,
    required this.sourceId,
  });

  static Future<Season> default_() =>
      RustLib.instance.api.crateApiTypesSeasonDefault();

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      seasonNumber.hashCode ^
      image.hashCode ^
      seriesId.hashCode ^
      sourceId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Season &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          seasonNumber == other.seasonNumber &&
          image == other.image &&
          seriesId == other.seriesId &&
          sourceId == other.sourceId;
}

class Settings {
  final String? recordingPath;
  final String? mpvParams;
  final bool? useStreamCaching;
  final ViewType? defaultView;
  final int? volume;
  final bool? refreshOnStart;
  final int? restreamPort;
  final bool? enableTrayIcon;
  final int? zoom;
  final SortType? defaultSort;
  final bool? enableHwdec;
  final bool? alwaysAskSave;
  final bool? enableGpu;

  const Settings({
    this.recordingPath,
    this.mpvParams,
    this.useStreamCaching,
    this.defaultView,
    this.volume,
    this.refreshOnStart,
    this.restreamPort,
    this.enableTrayIcon,
    this.zoom,
    this.defaultSort,
    this.enableHwdec,
    this.alwaysAskSave,
    this.enableGpu,
  });

  @override
  int get hashCode =>
      recordingPath.hashCode ^
      mpvParams.hashCode ^
      useStreamCaching.hashCode ^
      defaultView.hashCode ^
      volume.hashCode ^
      refreshOnStart.hashCode ^
      restreamPort.hashCode ^
      enableTrayIcon.hashCode ^
      zoom.hashCode ^
      defaultSort.hashCode ^
      enableHwdec.hashCode ^
      alwaysAskSave.hashCode ^
      enableGpu.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Settings &&
          runtimeType == other.runtimeType &&
          recordingPath == other.recordingPath &&
          mpvParams == other.mpvParams &&
          useStreamCaching == other.useStreamCaching &&
          defaultView == other.defaultView &&
          volume == other.volume &&
          refreshOnStart == other.refreshOnStart &&
          restreamPort == other.restreamPort &&
          enableTrayIcon == other.enableTrayIcon &&
          zoom == other.zoom &&
          defaultSort == other.defaultSort &&
          enableHwdec == other.enableHwdec &&
          alwaysAskSave == other.alwaysAskSave &&
          enableGpu == other.enableGpu;
}

class Source {
  final PlatformInt64? id;
  final String name;
  final String? url;
  final String? urlOrigin;
  final String? username;
  final String? password;
  final SourceType sourceType;
  final bool? useTvgId;
  final bool enabled;
  final String? userAgent;
  final int? maxStreams;
  final String? streamUserAgent;
  final PlatformInt64? lastUpdated;

  const Source({
    this.id,
    required this.name,
    this.url,
    this.urlOrigin,
    this.username,
    this.password,
    required this.sourceType,
    this.useTvgId,
    required this.enabled,
    this.userAgent,
    this.maxStreams,
    this.streamUserAgent,
    this.lastUpdated,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      url.hashCode ^
      urlOrigin.hashCode ^
      username.hashCode ^
      password.hashCode ^
      sourceType.hashCode ^
      useTvgId.hashCode ^
      enabled.hashCode ^
      userAgent.hashCode ^
      maxStreams.hashCode ^
      streamUserAgent.hashCode ^
      lastUpdated.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Source &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          url == other.url &&
          urlOrigin == other.urlOrigin &&
          username == other.username &&
          password == other.password &&
          sourceType == other.sourceType &&
          useTvgId == other.useTvgId &&
          enabled == other.enabled &&
          userAgent == other.userAgent &&
          maxStreams == other.maxStreams &&
          streamUserAgent == other.streamUserAgent &&
          lastUpdated == other.lastUpdated;
}
