// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

// These functions are ignored because they are not marked as `pub`: `get_download_path`, `get_filename`, `get_local_time`, `sanitize`

Future<void> refreshSource({required Source source}) =>
    RustLib.instance.api.crateApiUtilsRefreshSource(source: source);

Future<void> refreshAll() => RustLib.instance.api.crateApiUtilsRefreshAll();

Future<void> download({required Channel channel}) =>
    RustLib.instance.api.crateApiUtilsDownload(channel: channel);
