// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

// These functions are ignored because they are not marked as `pub`: `get_extension`, `get_filename`, `get_nuke_path`
// These functions are ignored because they have generic arguments: `serialize_to_file`

Future<void> refreshSource({required Source source}) =>
    RustLib.instance.api.crateApiUtilsRefreshSource(source: source);

Future<void> refreshAll() => RustLib.instance.api.crateApiUtilsRefreshAll();

Future<DateTime> getLocalTime({required PlatformInt64 timestamp}) =>
    RustLib.instance.api.crateApiUtilsGetLocalTime(timestamp: timestamp);

Future<String> sanitize({required String str}) =>
    RustLib.instance.api.crateApiUtilsSanitize(str: str);

Future<void> backupFavs({
  required PlatformInt64 sourceId,
  required String path,
}) => RustLib.instance.api.crateApiUtilsBackupFavs(
  sourceId: sourceId,
  path: path,
);

Future<void> restoreFavs({
  required PlatformInt64 sourceId,
  required String path,
}) => RustLib.instance.api.crateApiUtilsRestoreFavs(
  sourceId: sourceId,
  path: path,
);

Future<bool> isContainer() => RustLib.instance.api.crateApiUtilsIsContainer();

Future<void> createNukeRequest() =>
    RustLib.instance.api.crateApiUtilsCreateNukeRequest();

Future<void> checkNuke() => RustLib.instance.api.crateApiUtilsCheckNuke();

Future<String> getUserAgentFromSource({required Source source}) =>
    RustLib.instance.api.crateApiUtilsGetUserAgentFromSource(source: source);
