// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

// These functions are ignored because they are not marked as `pub`: `build_xtream_url`, `convert_xtream_live_to_channel`, `create_makeshift_season`, `episode_to_channel`, `get_cat_name`, `get_media_type_string`, `get_serde_json_i64`, `get_serde_json_string`, `get_serde_json_u64`, `get_url`, `get_xtream_http_data`, `insert_episode`, `insert_episodes`, `process_xtream`, `xtream_season_to_season`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `XtreamCategory`, `XtreamEPGItem`, `XtreamEPG`, `XtreamEpisodeInfo`, `XtreamEpisode`, `XtreamSeason`, `XtreamSeries`, `XtreamStream`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

Future<void> getXtream({required Source source, required bool wipe}) =>
    RustLib.instance.api.crateApiXtreamGetXtream(source: source, wipe: wipe);

Future<void> getEpisodes({required Channel channel}) =>
    RustLib.instance.api.crateApiXtreamGetEpisodes(channel: channel);
