// @generated
// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Channel {
    #[prost(int64, optional, tag = "1")]
    pub id: ::core::option::Option<i64>,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "3")]
    pub url: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "4")]
    pub group: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "5")]
    pub image: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(uint32, tag = "6")]
    pub media_type: u32,
    #[prost(int64, optional, tag = "7")]
    pub source_id: ::core::option::Option<i64>,
    #[prost(uint64, optional, tag = "8")]
    pub series_id: ::core::option::Option<u64>,
    #[prost(int64, optional, tag = "9")]
    pub group_id: ::core::option::Option<i64>,
    #[prost(bool, tag = "10")]
    pub favorite: bool,
    #[prost(uint64, optional, tag = "11")]
    pub stream_id: ::core::option::Option<u64>,
    #[prost(bool, optional, tag = "12")]
    pub tv_archive: ::core::option::Option<bool>,
    #[prost(int64, optional, tag = "13")]
    pub season_id: ::core::option::Option<i64>,
    #[prost(int64, optional, tag = "14")]
    pub episode_num: ::core::option::Option<i64>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ChannelList {
    #[prost(message, repeated, tag = "1")]
    pub channels: ::prost::alloc::vec::Vec<Channel>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Source {
    #[prost(int64, optional, tag = "1")]
    pub id: ::core::option::Option<i64>,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "3")]
    pub url: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "4")]
    pub url_origin: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "5")]
    pub username: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "6")]
    pub password: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(uint32, tag = "7")]
    pub source_type: u32,
    #[prost(bool, tag = "9")]
    pub enabled: bool,
    #[prost(string, optional, tag = "10")]
    pub user_agent: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "12")]
    pub stream_user_agent: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int64, optional, tag = "13")]
    pub last_updated: ::core::option::Option<i64>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Settings {
    #[prost(string, optional, tag = "2")]
    pub mpv_params: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(bool, optional, tag = "3")]
    pub use_stream_caching: ::core::option::Option<bool>,
    #[prost(uint32, optional, tag = "4")]
    pub default_view: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag = "5")]
    pub volume: ::core::option::Option<u32>,
    #[prost(bool, optional, tag = "6")]
    pub refresh_on_start: ::core::option::Option<bool>,
    #[prost(uint32, optional, tag = "9")]
    pub zoom: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag = "10")]
    pub default_sort: ::core::option::Option<u32>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Test {
    #[prost(uint32, tag = "1")]
    pub test: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FfiResult {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, optional, tag = "2")]
    pub error_message: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(oneof = "ffi_result::Data", tags = "3, 4, 5")]
    pub data: ::core::option::Option<ffi_result::Data>,
}
/// Nested message and enum types in `FFIResult`.
pub mod ffi_result {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Data {
        #[prost(message, tag = "3")]
        Settings(super::Settings),
        #[prost(message, tag = "4")]
        Source(super::Source),
        #[prost(message, tag = "5")]
        Test(super::Test),
    }
}
// @@protoc_insertion_point(module)
