name: build-linux

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v4
        with:
          channel: stable
          
      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y curl git unzip xz-utils zip libglu1-mesa cmake ninja-build clang pkg-config libgtk-3-dev libstdc++-12-dev liblzma-dev libmpv-dev
          cargo install cargo-cmd
          
      - name: Build
        run: |
          cargo cmd build-linux
          cd flutter
          flutter build linux --release

      - name: Package libmpv into the bundle
        run: |
          cp /usr/lib/x86_64-linux-gnu/libmpv.so.1 flutter/build/linux/x64/release/bundle/lib/

      - name: Upload Linux Build Bundle
        uses: actions/upload-artifact@v7
        with:
          name: linux-desktop-app
          path: flutter/build/linux/x64/release/bundle/

      
      
          
          

